server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easytransfertteste
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: easydemenagement207@gmail.com
    password: tmawjupfkptjcgto

  devtools:
    restart:
      enabled=true:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    content-type: text/html
    cache: false





